### ISSUE TITLE
TODO: Fail the Travis build if a performance regression is detected

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/PredictMD.jl#457]
- [ ] 1. Write a benchmark suite
- [ ] 2. Run the benchmark suite as part of every Travis build
- [ ] 3. Compare the benchmark performance of the `staging`/`trying` Travis build to the benchmark performance of the last commit on `master`
- [ ] 4. Upload the benchmark report to the `PredictMDBenchmarkReports` repository
- [ ] 5. If any performance regressions (time and/or memory) are detected, fail the `staging`/`trying` Travis build.

**Comment by DilumAluthge** [comment]
This is not a high priority right now. I will close this issue. We can revisit it in the future.
